### ISSUE TITLE
Error when update

### ISSUE THREAD

**Issue by strunz983** [scmanjarrez/CVEScannerV2#16]
Hello i get this error message when i try to update database my OS is 
Linux kali 6.11.2-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.11.2-1kali1 (2024-10-15) x86_64 GNU/Linux

pip list                                                                                                                                                                       1 ⨯
Package           Version
----------------- --------
anyio             4.3.0
certifi           2024.2.2
exceptiongroup    1.2.0
fake-useragent    1.5.1
h11               0.14.0
httpcore          1.0.4
httpx             0.27.0
idna              3.6
pip               24.3.1
pyrate-limiter    2.10.0
sniffio           1.3.1
tqdm              4.66.2
typing_extensions 4.10.0

This is error 

(venv)(root💀kali)-[~/CVEScannerV2/extra]
└─# python3 database.py -d cve.db   

CVEScannerV2  Copyright (C) 2022-2024 Sergio Chica Manjarrez @ pervasive.it.uc3m.es.
Universidad Carlos III de Madrid.
This program comes with ABSOLUTELY NO WARRANTY; for details check below.
This is free software, and you are welcome to redistribute it
under certain conditions; check below for details.

[*] Updating database...
[*] Retrieving CVEs/CPEs metadata...
[+] Metadata: 2043 CPEs | 245652 CVEs
[+] Retrieving CPEs:   0%|                                                                                                                                    | 0/2043 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/stuff/CVEScannerV2/extra/database.py", line 420, in query_api
    data = resp.json()
           ^^^^^^^^^^^
  File "/root/stuff/CVEScannerV2/extra/venv/lib/python3.12/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Thank you

**Comment by scmanjarrez** [comment]
Hi, I think there is a problem with the API, I'm getting inconsistent results querying the API. I'll contact NVD and update you on the status.

**Comment by scmanjarrez** [comment]
This is the response from NVD regarding API problems:
```
As indicated on our communications page https://www.nist.gov/itl/nvd, we are experiencing a large volume of API requests. This is, in part, due to a large update to the entire dataset as part of supporting ADP data from the CVE List. We are aware of stability issues experienced by users of the APIs and are working to make improvements where we are able. 
```

The full communication about this is available on the provided website.
```
November 15, 2024:  NVD Technical Update
CVE List Authorized Data Publisher (ADP) Support
We plan to deploy changes to our systems the week of November 18th. After this is complete, NVD systems will begin ingesting supported datatypes within the CVE List from all sources (CNAs and ADPs). 

What does this mean?
CVE records within the NVD dataset will contain more information (Reference(s), CWE, and CVSS) from additional sources. This new information will be displayed on the website and in the API responses, attributed to the organization who contributed the information. More information regarding ADPs can be reviewed at https://www.cve.org/ProgramOrganization/ADPs

    .

    Downstream data consumers will notice a large shift in the volume of CVE Record modifications as part of this change. Going forward, organizations should expect CVE records to update at a higher frequency.

    Other relevant changes:
    Duplicate References and Reference Tags

    As part of NVD enrichment efforts, reference tags are associated with each reference provided by a specific source. In instances where the same reference is provided by multiple sources, any reference tags associated to an existing reference will be applied to the newly provided, duplicate reference automatically.

    Changes to NVD CVE Record Change History
        Event Names are now more consistently ordered when they are recorded at the same timestamp.
        Event Content (Actions and Change Types) will now be more consistently ordered.
        Reference and Reference Tag (Type) changes will now be audited separately across all cases.
        “CVE Received” Events will be re-labeled as “New CVE Received.” Using the “CVE Received” eventName parameter for the /cvehistory/ API will still return the appropriate results.

    CVE API and Vulnerability Search Impacts
    Due to upstream removal of data points used by the NVD systems, the following parameters will no longer filter search results. 
        CVE API: HasCertAlerts, HasCertNotes, HasOval
        Vulnerability Search:  US-CERT Technical Alerts, US-CERT Vulnerability Notes, OVAL Queries

    These options will be removed in a future release.

        Legacy Data Feed Files (1.1 JSON)
        While the json data provided by the 2.0 API will reflect the ADP updates immediately, the legacy data feed file updates will be staggered over a series of days.
```

**Comment by strunz983** [comment]
Thank you scmanjarrez for your help.
So we need to wait 😊

**Comment by strunz983** [comment]
Happy new year
Thank you scmanjarrez I'm gonna take a look  😊

**Comment by scmanjarrez** [comment]
Hey, is the problem fixed?

**Comment by strunz983** [comment]
Hello I just make update and i got this error message.
Thank you :)

[*] Updating database...
[*] Retrieving CVEs/CPEs metadata...
[!] Error retrieving information from NVD API: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

**Comment by strunz983** [comment]
Hello when i try to update I get new issue
Thank you

python3 database.py -d cve.db
Traceback (most recent call last):
  File "/CVEScannerV2/extra/database.py", line 39, in <module>
    from fake_useragent import UserAgent
ImportError: cannot import name 'UserAgent' from 'fake_useragent' (unknown location)

**Comment by scmanjarrez** [comment]
Please install the dependencies listed in the requirements.txt. Create a virtual environment and install the exact version of the libraries listed in extra/requirements.txt

```bash
python3 -m venv venv
source venv/bin/activate
pip install -r extra/requirements.txt
```

```
❯ python extra/database.py                                                                                                                                                                                                                                                                                                                                                                                        
<SNIP>                                                                                                                                                                                                      
[*] Updating database...                                                                                                                                                                                    
[*] Retrieving CVEs/CPEs metadata...                                                                                                                                                                        
[+] Metadata: 1393 CPEs | 1324 CVEs
```

**Comment by strunz983** [comment]
Hello I already make this pip install -r extra/requirements.txt 
My problem is because sometime the update of database is working and some time not.
Thank you for your help :)

pip3 install -r requirements.txt
Requirement already satisfied: anyio==4.3.0 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 1)) (4.3.0)
Requirement already satisfied: certifi==2024.2.2 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 2)) (2024.2.2)
Requirement already satisfied: exceptiongroup==1.2.0 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: fake-useragent==1.5.1 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 4)) (1.5.1)
Requirement already satisfied: h11==0.14.0 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 5)) (0.14.0)
Requirement already satisfied: httpcore==1.0.4 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 6)) (1.0.4)
Requirement already satisfied: httpx==0.27.0 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 7)) (0.27.0)
Requirement already satisfied: idna==3.6 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 8)) (3.6)
Requirement already satisfied: pyrate-limiter==2.10.0 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 9)) (2.10.0)
Requirement already satisfied: sniffio==1.3.1 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 10)) (1.3.1)
Requirement already satisfied: tqdm==4.66.2 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 11)) (4.66.2)
Requirement already satisfied: typing_extensions==4.10.0 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 12)) (4.10.0)

**Comment by scmanjarrez** [comment]
Hello, could you provide an update of your issue?

**Comment by strunz983** [comment]
For now everything is working fine :)
Thank you
